import { readFile, writeFile } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';
const root = new URL('../web/', import.meta.url);
const wasm = await readFile(new URL('tsgo.wasm', root));
const gzip = gzipSync(wasm, { level: 9 });
const asset = {
  version: createHash('sha256').update(wasm).digest('hex'),
  bytes: wasm.length,
  gzipBytes: gzip.length,
};
await writeFile(new URL('tsgo.wasm.gz', root), gzip);
await writeFile(new URL('compiler-asset.js', root), `// Generated by scripts/compress-web.mjs\nexport const compilerAsset = ${JSON.stringify(asset, null, 2)};\n`);
console.log(`WASM download: ${(wasm.length / 1048576).toFixed(1)} → ${(gzip.length / 1048576).toFixed(1)} MiB`);
