// Generated by scripts/compress-web.mjs
export const compilerAsset = {
  "version": "ca5621f08e9fc67b36f5c2ce876ef3898df89dafc2bd8d282c8f06ce4ca3d957",
  "bytes": 18375206,
  "gzipBytes": 5875380
};
